# Generated by Django 2.2.1 on 2019-05-19 00:18

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('game_history', django.contrib.postgres.fields.jsonb.JSONField()),
                ('score', models.IntegerField()),
                ('status', models.TextField(choices=[('win', 'WIN'), ('loose', 'LOOSE')], default='win', max_length=5)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_game', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
